//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfInterface3.ServiceLicitacija {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOLice", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Ucenik.Pravno))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Ucenik.Fizicko))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Ucenik.Predstavnik))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Ucenik.Komisija))]
    public partial class DTOLice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Lice liceOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.Ucenik.Lice> liceOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Lice liceZahtevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Lice liceOdgovor {
            get {
                return this.liceOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.liceOdgovorField, value) != true)) {
                    this.liceOdgovorField = value;
                    this.RaisePropertyChanged("liceOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.Ucenik.Lice> liceOdgovorList {
            get {
                return this.liceOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.liceOdgovorListField, value) != true)) {
                    this.liceOdgovorListField = value;
                    this.RaisePropertyChanged("liceOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Lice liceZahtev {
            get {
                return this.liceZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.liceZahtevField, value) != true)) {
                    this.liceZahtevField = value;
                    this.RaisePropertyChanged("liceZahtev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOFizicko", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Ucenik.Predstavnik))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Ucenik.Komisija))]
    public partial class DTOFizicko : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Fizicko fizickoOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.Ucenik.Fizicko> fizickoOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Fizicko fizickoZahtevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Fizicko fizickoOdgovor {
            get {
                return this.fizickoOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.fizickoOdgovorField, value) != true)) {
                    this.fizickoOdgovorField = value;
                    this.RaisePropertyChanged("fizickoOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.Ucenik.Fizicko> fizickoOdgovorList {
            get {
                return this.fizickoOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.fizickoOdgovorListField, value) != true)) {
                    this.fizickoOdgovorListField = value;
                    this.RaisePropertyChanged("fizickoOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Fizicko fizickoZahtev {
            get {
                return this.fizickoZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.fizickoZahtevField, value) != true)) {
                    this.fizickoZahtevField = value;
                    this.RaisePropertyChanged("fizickoZahtev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOPravno", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    public partial class DTOPravno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Pravno pravnoOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.Ucenik.Pravno> pravnoOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Pravno pravnoZahtevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Pravno pravnoOdgovor {
            get {
                return this.pravnoOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.pravnoOdgovorField, value) != true)) {
                    this.pravnoOdgovorField = value;
                    this.RaisePropertyChanged("pravnoOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.Ucenik.Pravno> pravnoOdgovorList {
            get {
                return this.pravnoOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.pravnoOdgovorListField, value) != true)) {
                    this.pravnoOdgovorListField = value;
                    this.RaisePropertyChanged("pravnoOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Pravno pravnoZahtev {
            get {
                return this.pravnoZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.pravnoZahtevField, value) != true)) {
                    this.pravnoZahtevField = value;
                    this.RaisePropertyChanged("pravnoZahtev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOMesto", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    public partial class DTOMesto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Mesto mestoOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.Ucenik.Mesto> mestoOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Ucenik.Mesto mestoZahtevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Mesto mestoOdgovor {
            get {
                return this.mestoOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.mestoOdgovorField, value) != true)) {
                    this.mestoOdgovorField = value;
                    this.RaisePropertyChanged("mestoOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.Ucenik.Mesto> mestoOdgovorList {
            get {
                return this.mestoOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.mestoOdgovorListField, value) != true)) {
                    this.mestoOdgovorListField = value;
                    this.RaisePropertyChanged("mestoOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Ucenik.Mesto mestoZahtev {
            get {
                return this.mestoZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.mestoZahtevField, value) != true)) {
                    this.mestoZahtevField = value;
                    this.RaisePropertyChanged("mestoZahtev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOOglas", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    public partial class DTOOglas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.LicitacijaPriprema.Oglas oglasOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.LicitacijaPriprema.Oglas> oglasOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.LicitacijaPriprema.Oglas oglasZahtevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.LicitacijaPriprema.Oglas oglasOdgovor {
            get {
                return this.oglasOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.oglasOdgovorField, value) != true)) {
                    this.oglasOdgovorField = value;
                    this.RaisePropertyChanged("oglasOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.LicitacijaPriprema.Oglas> oglasOdgovorList {
            get {
                return this.oglasOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.oglasOdgovorListField, value) != true)) {
                    this.oglasOdgovorListField = value;
                    this.RaisePropertyChanged("oglasOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.LicitacijaPriprema.Oglas oglasZahtev {
            get {
                return this.oglasZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.oglasZahtevField, value) != true)) {
                    this.oglasZahtevField = value;
                    this.RaisePropertyChanged("oglasZahtev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOResenje", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    public partial class DTOResenje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.LicitacijaPriprema.Resenje resenjeOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.LicitacijaPriprema.Resenje> resenjeOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.LicitacijaPriprema.Resenje resenjeZahtevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.LicitacijaPriprema.Resenje resenjeOdgovor {
            get {
                return this.resenjeOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.resenjeOdgovorField, value) != true)) {
                    this.resenjeOdgovorField = value;
                    this.RaisePropertyChanged("resenjeOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.LicitacijaPriprema.Resenje> resenjeOdgovorList {
            get {
                return this.resenjeOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.resenjeOdgovorListField, value) != true)) {
                    this.resenjeOdgovorListField = value;
                    this.RaisePropertyChanged("resenjeOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.LicitacijaPriprema.Resenje resenjeZahtev {
            get {
                return this.resenjeZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.resenjeZahtevField, value) != true)) {
                    this.resenjeZahtevField = value;
                    this.RaisePropertyChanged("resenjeZahtev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTONadmetanje", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    public partial class DTONadmetanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.LicitacijaPriprema.Nadmetanje nadmetanjeOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.LicitacijaPriprema.Nadmetanje> nadmetanjeOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.LicitacijaPriprema.Nadmetanje nadmetanjeZahtevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.LicitacijaPriprema.Nadmetanje nadmetanjeOdgovor {
            get {
                return this.nadmetanjeOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.nadmetanjeOdgovorField, value) != true)) {
                    this.nadmetanjeOdgovorField = value;
                    this.RaisePropertyChanged("nadmetanjeOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.LicitacijaPriprema.Nadmetanje> nadmetanjeOdgovorList {
            get {
                return this.nadmetanjeOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.nadmetanjeOdgovorListField, value) != true)) {
                    this.nadmetanjeOdgovorListField = value;
                    this.RaisePropertyChanged("nadmetanjeOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.LicitacijaPriprema.Nadmetanje nadmetanjeZahtev {
            get {
                return this.nadmetanjeZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.nadmetanjeZahtevField, value) != true)) {
                    this.nadmetanjeZahtevField = value;
                    this.RaisePropertyChanged("nadmetanjeZahtev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOPrijava", Namespace="http://schemas.datacontract.org/2004/07/ServiceProxies")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Licitacija.PrijavaPravno))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DomenskeKlase.Licitacija.PrijavaFizicko))]
    public partial class DTOPrijava : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string porukaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Licitacija.Prijava prijavaOdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DomenskeKlase.Licitacija.Prijava> prijavaOdgovorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DomenskeKlase.Licitacija.Prijava prijavaZahtevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poruka {
            get {
                return this.porukaField;
            }
            set {
                if ((object.ReferenceEquals(this.porukaField, value) != true)) {
                    this.porukaField = value;
                    this.RaisePropertyChanged("poruka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Licitacija.Prijava prijavaOdgovor {
            get {
                return this.prijavaOdgovorField;
            }
            set {
                if ((object.ReferenceEquals(this.prijavaOdgovorField, value) != true)) {
                    this.prijavaOdgovorField = value;
                    this.RaisePropertyChanged("prijavaOdgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DomenskeKlase.Licitacija.Prijava> prijavaOdgovorList {
            get {
                return this.prijavaOdgovorListField;
            }
            set {
                if ((object.ReferenceEquals(this.prijavaOdgovorListField, value) != true)) {
                    this.prijavaOdgovorListField = value;
                    this.RaisePropertyChanged("prijavaOdgovorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DomenskeKlase.Licitacija.Prijava prijavaZahtev {
            get {
                return this.prijavaZahtevField;
            }
            set {
                if ((object.ReferenceEquals(this.prijavaZahtevField, value) != true)) {
                    this.prijavaZahtevField = value;
                    this.RaisePropertyChanged("prijavaZahtev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLicitacija.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLiceSoWcf", ReplyAction="http://tempuri.org/IService1/InsertLiceSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOLice InsertLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLiceSoWcf", ReplyAction="http://tempuri.org/IService1/InsertLiceSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> InsertLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLiceSoWcf", ReplyAction="http://tempuri.org/IService1/DeleteLiceSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOLice DeleteLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLiceSoWcf", ReplyAction="http://tempuri.org/IService1/DeleteLiceSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> DeleteLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajLiceSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajLiceSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOLice AzurirajLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajLiceSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajLiceSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> AzurirajLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLiceSoWcf", ReplyAction="http://tempuri.org/IService1/GetLiceSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOLice GetLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLiceSoWcf", ReplyAction="http://tempuri.org/IService1/GetLiceSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> GetLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLiceSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllLiceSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOLice GetAllLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLiceSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllLiceSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> GetAllLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/InsertFizickoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOFizicko InsertFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/InsertFizickoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> InsertFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/DeleteFizickoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOFizicko DeleteFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/DeleteFizickoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> DeleteFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajFizickoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOFizicko AzurirajFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajFizickoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> AzurirajFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/GetFizickoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOFizicko GetFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/GetFizickoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> GetFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllFizickoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOFizicko GetAllFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFizickoSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllFizickoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> GetAllFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/InsertPravnoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPravno InsertPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/InsertPravnoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> InsertPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePravnoSoWcf", ReplyAction="http://tempuri.org/IService1/DeletePravnoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPravno DeletePravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePravnoSoWcf", ReplyAction="http://tempuri.org/IService1/DeletePravnoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> DeletePravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajPravnoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPravno AzurirajPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajPravnoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> AzurirajPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/GetPravnoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPravno GetPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/GetPravnoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> GetPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllPravnoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPravno GetAllPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPravnoSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllPravnoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> GetAllPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsertMestoSoWcf", ReplyAction="http://tempuri.org/IService1/IsertMestoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOMesto IsertMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsertMestoSoWcf", ReplyAction="http://tempuri.org/IService1/IsertMestoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> IsertMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMestoSoWcf", ReplyAction="http://tempuri.org/IService1/DeleteMestoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOMesto DeleteMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMestoSoWcf", ReplyAction="http://tempuri.org/IService1/DeleteMestoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> DeleteMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajMestooSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajMestooSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOMesto AzurirajMestooSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajMestooSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajMestooSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> AzurirajMestooSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMestoSoWcf", ReplyAction="http://tempuri.org/IService1/GetMestoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOMesto GetMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMestoSoWcf", ReplyAction="http://tempuri.org/IService1/GetMestoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> GetMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMestoSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllMestoSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOMesto GetAllMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMestoSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllMestoSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> GetAllMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllOglasSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllOglasSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOOglas GetAllOglasSoWcf(WpfInterface3.ServiceLicitacija.DTOOglas oglas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllOglasSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllOglasSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOOglas> GetAllOglasSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOOglas oglas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllResenjeSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllResenjeSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOResenje GetAllResenjeSoWcf(WpfInterface3.ServiceLicitacija.DTOResenje resenje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllResenjeSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllResenjeSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOResenje> GetAllResenjeSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOResenje resenje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNadmetanjeSoWcf", ReplyAction="http://tempuri.org/IService1/GetNadmetanjeSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTONadmetanje GetNadmetanjeSoWcf(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNadmetanjeSoWcf", ReplyAction="http://tempuri.org/IService1/GetNadmetanjeSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTONadmetanje> GetNadmetanjeSoWcfAsync(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllNadmetanjeForOglasSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllNadmetanjeForOglasSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTONadmetanje GetAllNadmetanjeForOglasSoWcf(WpfInterface3.ServiceLicitacija.DTOOglas oglas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllNadmetanjeForOglasSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllNadmetanjeForOglasSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTONadmetanje> GetAllNadmetanjeForOglasSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOOglas oglas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/InsertPrijavaSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPrijava InsertPrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTOPrijava prijava);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/InsertPrijavaSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> InsertPrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPrijava prijava);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/DeletePrijavaSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPrijava DeletePrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTOPrijava prijava);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/DeletePrijavaSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> DeletePrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPrijava prijava);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajPrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajPrijavaSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPrijava AzurirajPrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTOPrijava prijava);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AzurirajPrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/AzurirajPrijavaSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> AzurirajPrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPrijava prijava);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLiceForPrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllLiceForPrijavaSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOLice GetAllLiceForPrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLiceForPrijavaSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllLiceForPrijavaSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> GetAllLiceForPrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPrijavaForNadmetanjeSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllPrijavaForNadmetanjeSoWcfResponse")]
        WpfInterface3.ServiceLicitacija.DTOPrijava GetAllPrijavaForNadmetanjeSoWcf(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPrijavaForNadmetanjeSoWcf", ReplyAction="http://tempuri.org/IService1/GetAllPrijavaForNadmetanjeSoWcfResponse")]
        System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> GetAllPrijavaForNadmetanjeSoWcfAsync(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfInterface3.ServiceLicitacija.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfInterface3.ServiceLicitacija.IService1>, WpfInterface3.ServiceLicitacija.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfInterface3.ServiceLicitacija.DTOLice InsertLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.InsertLiceSoWcf(lice);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> InsertLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.InsertLiceSoWcfAsync(lice);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOLice DeleteLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.DeleteLiceSoWcf(lice);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> DeleteLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.DeleteLiceSoWcfAsync(lice);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOLice AzurirajLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.AzurirajLiceSoWcf(lice);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> AzurirajLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.AzurirajLiceSoWcfAsync(lice);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOLice GetLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.GetLiceSoWcf(lice);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> GetLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.GetLiceSoWcfAsync(lice);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOLice GetAllLiceSoWcf(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.GetAllLiceSoWcf(lice);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> GetAllLiceSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOLice lice) {
            return base.Channel.GetAllLiceSoWcfAsync(lice);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOFizicko InsertFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.InsertFizickoSoWcf(fizicko);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> InsertFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.InsertFizickoSoWcfAsync(fizicko);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOFizicko DeleteFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.DeleteFizickoSoWcf(fizicko);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> DeleteFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.DeleteFizickoSoWcfAsync(fizicko);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOFizicko AzurirajFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.AzurirajFizickoSoWcf(fizicko);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> AzurirajFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.AzurirajFizickoSoWcfAsync(fizicko);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOFizicko GetFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.GetFizickoSoWcf(fizicko);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> GetFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.GetFizickoSoWcfAsync(fizicko);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOFizicko GetAllFizickoSoWcf(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.GetAllFizickoSoWcf(fizicko);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOFizicko> GetAllFizickoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOFizicko fizicko) {
            return base.Channel.GetAllFizickoSoWcfAsync(fizicko);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPravno InsertPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.InsertPravnoSoWcf(pravno);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> InsertPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.InsertPravnoSoWcfAsync(pravno);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPravno DeletePravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.DeletePravnoSoWcf(pravno);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> DeletePravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.DeletePravnoSoWcfAsync(pravno);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPravno AzurirajPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.AzurirajPravnoSoWcf(pravno);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> AzurirajPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.AzurirajPravnoSoWcfAsync(pravno);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPravno GetPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.GetPravnoSoWcf(pravno);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> GetPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.GetPravnoSoWcfAsync(pravno);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPravno GetAllPravnoSoWcf(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.GetAllPravnoSoWcf(pravno);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPravno> GetAllPravnoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPravno pravno) {
            return base.Channel.GetAllPravnoSoWcfAsync(pravno);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOMesto IsertMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.IsertMestoSoWcf(mesto);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> IsertMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.IsertMestoSoWcfAsync(mesto);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOMesto DeleteMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.DeleteMestoSoWcf(mesto);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> DeleteMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.DeleteMestoSoWcfAsync(mesto);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOMesto AzurirajMestooSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.AzurirajMestooSoWcf(mesto);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> AzurirajMestooSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.AzurirajMestooSoWcfAsync(mesto);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOMesto GetMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.GetMestoSoWcf(mesto);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> GetMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.GetMestoSoWcfAsync(mesto);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOMesto GetAllMestoSoWcf(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.GetAllMestoSoWcf(mesto);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOMesto> GetAllMestoSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOMesto mesto) {
            return base.Channel.GetAllMestoSoWcfAsync(mesto);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOOglas GetAllOglasSoWcf(WpfInterface3.ServiceLicitacija.DTOOglas oglas) {
            return base.Channel.GetAllOglasSoWcf(oglas);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOOglas> GetAllOglasSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOOglas oglas) {
            return base.Channel.GetAllOglasSoWcfAsync(oglas);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOResenje GetAllResenjeSoWcf(WpfInterface3.ServiceLicitacija.DTOResenje resenje) {
            return base.Channel.GetAllResenjeSoWcf(resenje);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOResenje> GetAllResenjeSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOResenje resenje) {
            return base.Channel.GetAllResenjeSoWcfAsync(resenje);
        }
        
        public WpfInterface3.ServiceLicitacija.DTONadmetanje GetNadmetanjeSoWcf(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetaje) {
            return base.Channel.GetNadmetanjeSoWcf(nadmetaje);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTONadmetanje> GetNadmetanjeSoWcfAsync(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetaje) {
            return base.Channel.GetNadmetanjeSoWcfAsync(nadmetaje);
        }
        
        public WpfInterface3.ServiceLicitacija.DTONadmetanje GetAllNadmetanjeForOglasSoWcf(WpfInterface3.ServiceLicitacija.DTOOglas oglas) {
            return base.Channel.GetAllNadmetanjeForOglasSoWcf(oglas);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTONadmetanje> GetAllNadmetanjeForOglasSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOOglas oglas) {
            return base.Channel.GetAllNadmetanjeForOglasSoWcfAsync(oglas);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPrijava InsertPrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTOPrijava prijava) {
            return base.Channel.InsertPrijavaSoWcf(prijava);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> InsertPrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPrijava prijava) {
            return base.Channel.InsertPrijavaSoWcfAsync(prijava);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPrijava DeletePrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTOPrijava prijava) {
            return base.Channel.DeletePrijavaSoWcf(prijava);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> DeletePrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPrijava prijava) {
            return base.Channel.DeletePrijavaSoWcfAsync(prijava);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPrijava AzurirajPrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTOPrijava prijava) {
            return base.Channel.AzurirajPrijavaSoWcf(prijava);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> AzurirajPrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTOPrijava prijava) {
            return base.Channel.AzurirajPrijavaSoWcfAsync(prijava);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOLice GetAllLiceForPrijavaSoWcf(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje) {
            return base.Channel.GetAllLiceForPrijavaSoWcf(nadmetanje);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOLice> GetAllLiceForPrijavaSoWcfAsync(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje) {
            return base.Channel.GetAllLiceForPrijavaSoWcfAsync(nadmetanje);
        }
        
        public WpfInterface3.ServiceLicitacija.DTOPrijava GetAllPrijavaForNadmetanjeSoWcf(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje) {
            return base.Channel.GetAllPrijavaForNadmetanjeSoWcf(nadmetanje);
        }
        
        public System.Threading.Tasks.Task<WpfInterface3.ServiceLicitacija.DTOPrijava> GetAllPrijavaForNadmetanjeSoWcfAsync(WpfInterface3.ServiceLicitacija.DTONadmetanje nadmetanje) {
            return base.Channel.GetAllPrijavaForNadmetanjeSoWcfAsync(nadmetanje);
        }
    }
}
